name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  # schedule:
  #   - cron: '44 0 * * *'
  workflow_run:
    workflows: ["run tests"]
    types:
      - completed
    branches:
      - "master"
      - "main"
      - 'releases/**'
    tags:
      - 'v*.*.*'
  push:
    branches:
      - "master"
      - "main"
      - 'releases/**'
    # Publish semver tags as releases.
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - "master"
      - "main"
      - 'releases/**'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  OS_LIST: linux darwin
  ARCH_LIST: amd64 arm64 arm
  COMMIT_NUMBER: ${{ github.sha }}
  TAG_VALUE: ${{ github.ref_name }}


jobs:
  build-app:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build app
        id: build
        run: make build

      - name: Cache build files
        uses: actions/cache@v3
        with:
          path: |
            .build
            docker
          key: ${{ runner.os }}-build

  build-docker:
    runs-on: ubuntu-latest
    environment: "docker hub"

    steps:
      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - uses: actions/download-artifact@v3
      #   with:
      #     name: app-build

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: deploy/production.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm,darwin/amd64,darwin/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

    needs: [build-app]
