version: '3.8'

services:
  redis:
    image: redis:latest

  clickhouse:
    image: clickhouse/clickhouse-server:latest

  pgdb:
    restart: always
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}

  redify:
    image: demdxx/redify
    depends_on:
      - pgdb
      - redis
      # - clickhouse
    ports:
      - "8080:8080"
      - "8081:6380"
      - "8086:6060"
